### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by User4716** [czQery/ToolKit#10]
### ⚠️Conflicts
**/vanish** command conflicts with SuperVanish 
And also **/fly, /sit, /gmc, /gms, /gmsp, /gma, /spawn, /troll** commands conflict with other plugins I have.

So can you please make an option in the config file where I can disable/change any command of this plugin I want 👍

![suggestion](https://user-images.githubusercontent.com/97033682/223653107-447cf6ea-c43c-4a39-92d6-2fa896c1ed3a.png)

### 🪄Other Suggestions
Also can you make a permission for '/toolkit' command which shows info about plugin, sience I dont want players seeing information about this plugin.

ㅤ
You could also make a new troll to this plugin called "**NoQuit**" (or similar named.) And the troll would prevent the victim from leaving the game, there is 2 ways that you could make this troll.

1. Spam the user constantsly with a popup inventory
2. Spam the user with packets that close the inventory/GUI if an GUI is open ('_Close_Container_' packets)

> 💡**2 Method is better:**
> I think generally the second option is better, sience that will close not only the players inventory instantly when opened, but also the "Game Menu" where you can Leave the game, and best of all it also will close the chat, or any GUI you could imagine, so the victim can't run any commands or send messages! 
> I don't think the first method would be better, sience a lot of Freeze plugins already use the first method and it is very confusing/annoying to get constantly spammed with a GUI. And I've seen one plugin do this second method already: https://www.spigotmc.org/resources/78508/
> (Keep in mind that you still can ALT+F4)

**Comment by czQery** [comment]
Hi, thx for your feedback

Conflicting commands don't really have a good solution because even if I disable the command executor for individual commands it still conflicts because the command is specified in plugin.yml which cannot be modified during runtime (at least as far as I know), but there are a lot of options how to solve this without complicated workarounds:

0.  ~~Just delete the conflicting plugins lol~~
1.  You can use alternative versions of the commands offered by the plugins: `/v, /sv, /supervanish, /trollitem`
2.  Or use the built-in function to specify which plugin you want to run the command on: `/supervanish:vanish, /ultimatetroll:troll`

I intentionally want to leave the /toolkit command available to everyone because this is not a premium plugin so instead of a profit I have at least some visibility.

I find the no quit feature interesting and will definitely try to implement it :)

**Comment by User4716** [comment]
Ok thanks 👍

And btw this plugin: https://www.spigotmc.org/resources/83562/ (Staff++) Has an option in the config file to change the registered commands. (https://github.com/Shortninja66/StaffPlus/blob/master/resources/config.yml)
So I think it is actually possible to change the commands in the plugin.

And it is Open source on GitHub: https://github.com/garagepoort/StaffPlusPlus

**Comment by czQery** [comment]
You're right, I'll look into it.

**Comment by czQery** [comment]
Thank you for your support 😄, I hope the plugin is more usable for you after this update.
