### ISSUE TITLE
Error: „Could not pass event PlayerJoinEvent to ToolKit v2.9“

### ISSUE THREAD

**Issue by WaldperlachFabi** [czQery/ToolKit#5]
If someone join the Server I get this error:

`[Tue, 7. Dec 2021 15:35:56 UTC ERROR] Could not pass event PlayerJoinEvent to ToolKit v2.9 `

And can you please add the command /tcrash <player> and console support? I would like to troll my friends when im not on my PC and I’ve got another plugin Thant makes a troll command /crash but then only kicks the player. Would be really great! Thank you for your help!

**Comment by czQery** [comment]
The world you typed into the join section in your config probably doesnt exists. I will add a better check in the next update.

Once again there is already /crash support for console, if you have another plugin that has/crash command just use /toolkit:crash instead of /crash.

Or you can open the jar file in 7zip or Winrar and add aliases for that command in plugin.yml.
![image](https://user-images.githubusercontent.com/60880179/145100027-c5b49645-e74c-4322-952c-5dea243cd8b5.png)

I attached the edited version with /tcrash alias.
[ToolKit-2.9_tcrash.zip](https://github.com/czQery/ToolKit/files/7671388/ToolKit-2.9_tcrash.zip)
